import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'pt',
        'en',
        'es',
        'it',
        'fr',
        'la',
        'ko',
        'ar',
        'zh_Hans',
        'ru',
        'af',
        'zh_Hant',
        'id',
        'uk',
        'ro',
        'de',
        'gl',
        'kg',
        'vi'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? ptText = '',
    String? enText = '',
    String? esText = '',
    String? itText = '',
    String? frText = '',
    String? laText = '',
    String? koText = '',
    String? arText = '',
    String? zh_HansText = '',
    String? ruText = '',
    String? afText = '',
    String? zh_HantText = '',
    String? idText = '',
    String? ukText = '',
    String? roText = '',
    String? deText = '',
    String? glText = '',
    String? kgText = '',
    String? viText = '',
  }) =>
      [
        ptText,
        enText,
        esText,
        itText,
        frText,
        laText,
        koText,
        arText,
        zh_HansText,
        ruText,
        afText,
        zh_HantText,
        idText,
        ukText,
        roText,
        deText,
        glText,
        kgText,
        viText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // PagedeCadastro
  {
    'ngbxhqtg': {
      'pt': 'Criar Uma Conta',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'co3i3wf5': {
      'pt': 'Vamos começar preenchendo o formulário abaixo.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'r8ftowzh': {
      'pt': 'E-mail',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yubwuk8i': {
      'pt': 'Senha',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b3whin29': {
      'pt': 'Confirmar senha',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6pna799d': {
      'pt': 'Criar conta',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y75gav7e': {
      'pt': 'Já tem uma conta?',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9oe0qcgi': {
      'pt': 'Login.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // PagedeLogin
  {
    '9lkobg8b': {
      'pt': 'Seja Sábio',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6c17be6k': {
      'pt': 'Um aplicativo para te tornar, verdadeiramente, mais sábio.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7jw6xap1': {
      'pt': 'E-mail',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'syyevac4': {
      'pt': 'Senha',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wvuv4993': {
      'pt': 'Login',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '99f4jpy1': {
      'pt': 'Não tem uma conta?',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'p3byxhn0': {
      'pt': 'Criar uma aqui.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nb6a9ikp': {
      'pt': 'Forgot Password?',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'oozv6xov': {
      'pt': 'Esqueceu a sua senha?',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // PaginaPrincipaldoaplicativo
  {
    'baoli7w2': {
      'pt': 'Exit',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lfzftvx6': {
      'pt': 'Sabedoria',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hbnbqh7e': {
      'pt': 'Artigo 1',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ef6440a1': {
      'pt': '  Disciplina',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vkp71lqj': {
      'pt': '   Artigo 2',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2gkgkcjp': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // PaginaPrincipaldoaplicativoCopy
  {
    'oerce0b5': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd599fs71': {
      'pt': 'Religião',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wdin2863': {
      'pt': 'Artigo 3',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wsuvb6vz': {
      'pt': 'Educação',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's15lbiaq': {
      'pt': 'Artigo 4',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd0wksexf': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // PaginaPrincipaldoaplicativoCopyCopy
  {
    'hpksh8eo': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '00ab8vly': {
      'pt': 'Música',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xjlc879j': {
      'pt': 'Artigo 5',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6ljhcwfe': {
      'pt': 'Compilados de Frases Sábias',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7fw7tv0h': {
      'pt': 'Artigo 6',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaderedefinicao
  {
    'fhmcn75w': {
      'pt': 'Resetar Senha',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xahj7io7': {
      'pt':
          'Por favor, digite seu endereço de e-mail para redefinir sua senha.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'h5bvnvqe': {
      'pt': 'E-mail',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'iekofn4z': {
      'pt': 'Resetar senha',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'df9gaozo': {
      'pt': 'Lembra da sua senha?',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'c43l6gl4': {
      'pt': 'Login.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo1
  {
    't5npywvs': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '69shhetd': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1i6a7asx': {
      'pt': 'Sabedoria',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '53mgbvex': {
      'pt': 'Busque primeiro sabedoria.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4kyxcu97': {
      'pt':
          'Como esse é o primeiro artigo de uma sequência de artigos com ordem.\n\nIrei explicar o objetivo desse aplicativo, bem como usá-lo e como ler os artigos.\n\nO objetivo desse aplicativo é criar no leitor que para ele ser feliz, e para ele obter honras e riquezas é preciso primeiro obter sabedoria, bem como ter disciplina para obter-la.  Bem como outras virtudes, e capacidades desenvolvidas. Não estou dizendo que sou o mais sábio, o melhor, enfim. Mas que esta é a verdade, está nas leis de Deus, nas palavras dos grandes filósofos e nas palavras dos Santos.\n\nAqui estão alguns trechos:\n\nFeliz é a pessoa que acha a sabedoria, e que consegue compreender as coisas, pois isso é melhor do que a prata, e tem mais valor do que o ouro. A sabedoria é mais preciosa do que as joias; tudo o que a gente deseja não se pode comparar com ela. Provérbios 3:13-26 \n\nO importante não é viver, mas viver bem. Platão\n\nTente mover o mundo, o primeiro passo será mover a si mesmo. Platão\n',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo2
  {
    'duwwlszb': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bja5fl2d': {
      'pt':
          'Escute os sábios e procure entender o que eles ensinam. Provérbios \n\nPortando, devemos escutar os sábios, se quisermos termos uma vida feliz. Todos temos problemas, mas é como lidamos com eles que importa. \n\nPara usar esse aplicativo, terás que ler os artigos em sua devida ordem; ordem natural que está posta aqui no aplicativo.\n\nTens que ler devagar, sem pressa. Pesquisando cada palavra, e anotando o que mais te interessou. Se não conseguiu entender, leia novamente. Repita até entender. Esse é um dos pontos importantes que quero passar com esse aplicativo; O tempo é o nosso bem mais importante, por isso devemos usá-lo com sabedoria. Usar o tempo para fazer coisas boas, que irão nos engrandecer, e não sair o desperdiçando atoa por aí. \n\nE não se sinta culpado perante seus erros, se fez o mal, se errou, faça o bem. Pronto.\n\nDefeitos não fazem mal, quando há vontade e poder de os corrigir. Machado de Assis.\n\nAqui é a solução para você enriquecer? Aqui é o “segredo”? \nNão existe isso.\nMas é isso que eu tenho a oferecer; sabedoria.\n\nSuponhamos que você está desempregado. Acabou de ser largado, seus “amigos” te deram as costas. Sua família se afastou de você. Você está sozinho. Qual é a solução? A resposta; Busque sabedoria. Para saber lidar com sua situação. Essa é a única e verdadeira saída e se você tem tempo, ou seja, se você está vivo, creia, tem solução.\nTenha paciência e disciplina\n',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo3
  {
    'fyia5q0p': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xvbykju9': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6ov44r38': {
      'pt': 'Disciplina',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'aqrgeuko': {
      'pt': 'Aprenda a importância da disciplina.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'l2nkrdex': {
      'pt':
          '“Dedique à disciplina o seu coração e os seus ouvidos às palavras que dão conhecimento.”\n\nSabendo que você em primeiro lugar, tem que buscar disciplina, então, praticando o conselho e buscando a mesma, se deparara com o seguinte problema; repetir os mesmos erros, e não saber o que fazer. A questão fundamental é sobre o tempo. Dado que o tempo é o nosso bem mais valioso, você tem que entender que não podemos o desperdiçar, e temos que usar ele para o nosso próprio bem. Para a nossa verdadeira felicidade, ahh, mas eu assisto futebol, tenho meus amigos no bar da esquina, como meu churrasquinho nos finais de semana. Mas será se você é feliz?\n\nSerá se você não vive, uma vida que é posta como feliz, e por assim dizer, por muitas pessoas a repetirem. Por ter todo um jogo midiático em prol dessa imagem, para todos a acharem normal, mas será, se verdadeiramente, eu seu interior, você é feliz?\n\nOu você vive estressado, cansado, esperando chegar os finais de semana, para, digamos, descontar tudo na dopamina que o churrasco e a cerveja lhe oferece. Mas você sente que a sua vida vai passando, você quase não construiu nada, você se sente vazio.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo4
  {
    '29en31cc': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd3cyrflk': {
      'pt':
          'Você é feliz?\nEntão, mas essa é a verdadeira questão desse app, não desperdice seu tempo com coisas fúteis e que te colocaram como estilo de vida padrão. Mas busque a força e o poder. Essa é a verdadeira felicidade. É o que muito o filósofo Olavo de Carvalho dizia em seus vídeos; “A verdadeira felicidade é a busca da força e do poder.” Não procure ter segurança, não procure ter estabilidade, procure ser milionário. Pois não existe segurança, os problemas vão aparecer e como você vai lidar com eles sem dinheiro? Sem sabedoria?\n\nVocê tem que ter disciplina para buscar todos esses valores. Pois é isso o que importa. Em vez de você ficar vendo o TikTok, gastando todo seu dinheiro em coisas fúteis. Procure substituir o TikTok pela leitura, comece lendo a Bíblia. Vendo passagens interessantes. Deixe de comprar coisas fúteis e ajunte aos poucos, procure entender sobre finanças, com o seu dinheiro ajuntado, invista em projetos. Projetos que te daram mais força e poder.\nVocê terá que ter disciplina para conseguir adquirir qualquer coisa.\n\nFrases dos sábios;\n\n“O trabalho árduo produz lucro. Mas a conversa fiada leva à pobreza.” Provérbios 14.23\n\n“Nós nos transformamos naquilo que praticamos com frequência. A perfeição, portando, não é um ato isolado. É um hábito.” Aristoteles\n\n“Não adianta nada ficar lamentando os males, É preciso arregaçar as mangas e dar de tudo para eliminá-los.”\nPadre Dom Bosco.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo5
  {
    'n97ba2ob': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v4rf0pbl': {
      'pt':
          '“Compra a verdade e não a vendas; sim, a sabedoria, e a disciplina, e a prudência.” Provérbios\n\nVocê que vai decidir o rumo da sua vida. \nUma vida com disciplina e sabedoria, ou uma vida insensata e sem prudência. A primeira te trará disciplina e honra. A segunda te trará dores e aflições.\n\nFica a reflexão.\n\nFim.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo6
  {
    '8wrhjcbo': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm5sc8px7': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'q178krnn': {
      'pt': 'Religião',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ie7lxz1s': {
      'pt': 'Sem Deus, nada é possível.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cjbjyf0v': {
      'pt':
          'O País começa, com religião e alta cultura. Foi a religião que criou o Brasil, foi a religião que criou todos os países do mundo.\n\nNão temos que agradar ninguém, temos que agradar em primeiro lugar a Deus. O senhor. Esse é o primeiro mandamento. Amar a Deus sobre todas as coisas. E como diz o santo Padre Pio; “Não se esqueça de que você será tratado por Deus com a mesma medida que você trata os outros.”\n\nEntão, mesmo que você viva uma vida perfeita perante os outros e segundo você mesmo. Mas que desagrade a Deus. Ou seja, você pratica o mal, porém, tenta fazer tudo corretamente, saiba você que praticando o mal contra o seu próximo você estará pecando contra Deus. Afinal, Deus não se agrada que você pratique o mal. Se você pratica o mal, procuras corrigir-se e faça o bem. Não fique se perturbando, remorsos, é coisa do diabo. Isso é uma coisa, que se você não prestar atenção vai piorar a sua situação. Pois o sentimento de culpa, apodrece a alma, apodrece a esperança e outras virtudes.\n\nNós vivemos em uma sociedade em decadência, que, entre aqueles que praticam o mal, entre aqueles que praticam o pecado por vontade pura e própria, mas não é punido. ',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo7
  {
    '9o00xdka': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v6x0uoit': {
      'pt':
          ' É venerado entre os maus. Como alguém que acabou de fazer uma grande descoberta ou como alguém que acabou de sair vitorioso em uma batalha. Vejamos o nosso cenário político atual, vejamos os nossos políticos que fazem politicagem.\n\nVivem uma oligarquia. Para eles, o normal, por exemplo, é roubar, para eles, o normal é roubar e não ser descoberto. Pois isso, não é tanto uma preocupação moral e punitiva. Mas uma preocupação de imagem política, da políticagem.\n\nPois, sendo os mesmos descobertos, passaram uma imagem ruim perante os seus eleitores. O bom é roubar, sem ser descoberto, e com isso, além de enriquecer seus próprios bolsos, podem, mais uma vez, enganar seus eleitores, será se Deus se agrada com isso?\n\nA resposta; Não. Qual será o destino desses malfeitores? A resposta; “O dinheiro ganho com desonestidade diminuirá, mas quem o ajunta aos poucos terá cada vez mais. A esperança que se retarda deixa o coração doente, mas o anseio satisfeito é árvore de vida. Quem zomba da instrução pagará por ela, mas aquele que respeita o mandamento será recompensado.” Provérbios 13:11-20.\n\nSaiba você, meu nobre leitor, o destino deles não será tão bom, aqui na terra, e depois da morte; no inferno. Mas podemos julgar os outros? A resposta; Sim. \nNão julgar os outros com base nas leis de Deus, ou seja, se omitir, também é pecado.\nAqui temos algumas frases do Doctor Angelicus; Santo Tomaz de Aquino.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo8
  {
    'edbtg1g2': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'x2krs2gr': {
      'pt':
          'Frases:\n\n“Não se opor ao erro, é aprova-lo, não defender a verdade é nega-lá.” Santo Tomaz de Aquino\n\n“Pois é muito mais grave corromper a fé, da qual vem a vida da alma, que falsificar dinheiro, pelo qual a vida temporal é sustentada.” Santo Tomaz de Aquino\n\n“Se podes viver no meio da injustiça sem sentir repugnância, então és tão imoral como injusto.” Santo Tomaz de Aquino\n\nPortanto, creio, que isso é suficiente para criar o senso de proporção de que praticar o pecado e as injustiças contra as leis de Deus causa; Estarás pecando e desagradando o criador dos céus e da terra, Deus. De nada vale sua “Sabedoria”, sua “Disciplina”. De nada vale. Perderá tudo aqui e a sua alma será condenada ao inferno. \nE não me venha com teorias malucas dizendo que seus pecados serão perdoa-dos. Não. Não serão. Ao menos que se arrependa, verdadeiramente, coisa que as almas malignas não fazem. Se você foi enganado, se estás praticando o mal, digamos, por falta de conhecimento e por influência. Arrependa-se e procures te corrigir. Idem!\n\nTens que procurar ir as santas missas.\nAprender a preservar o Domingo.\nOrar o Pai Nosso. A principal oração cristã.\nAqui está o link do catecismo da Santa Igreja; \n\nhttps://www.vatican.va/archive/cathechism_po/index_new/prima-pagina-cic_po.html',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo9
  {
    'p34auy6h': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ckfdy5zj': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's5gbldtb': {
      'pt': 'Educação',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eskzp04u': {
      'pt': 'A importância da educação clássica.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'l6i4cev0': {
      'pt':
          'Recomendo que o leia.\n\nQue pesquise suas dúvidas.\n\nQue pergunte aos sábios.\n\n“A humildade é o primeiro degrau para a sabedoria.” Santo Tomaz de Aquino\nIdem!\n\nNós vivemos num país em que 95% da população são de analfabetos funcionais, ou seja, que não sabem interpretar uma página, por exemplo, de um livro qualquer ou ainda de um jornal qualquer. Com isso, vemos a importância alarmante da educação em nosso país. Pois, como um indivíduo pode viver bem, trabalhar bem, fazer progredir nosso país, se o mesmo não domina o básico de um elemento fundamental para nós, seres racionais, que é a leitura. Imagine as outras áreas como história, matemática e outras demais áreas que são ensinadas no nosso ensino regular.\n\nOu seja, você passou tantos anos numa escola, e não conseguiu adquirir o básico que um ser humano racional precisa para viver, você foi ensinado que o importante, na verdade, era adquirir o diploma para o mercado de trabalho ou até mesmo para concursos.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo10
  {
    '6ywu1wyl': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vazxav7h': {
      'pt':
          'Mas o verdadeiro dever da educação é o desenvolvimento espiritual. No qual, sem ele, nós, seres humanos racionais. Somos na verdade, seres disnorteados, sem saber o que fazer perante a nossa realidade. Vivendo assim, na verdade, como um ser irracional.\n\nPor isso vejo a importância da educação clássica para o nosso desenvolvimento,sobretudo, espiritual. E que também vai te trazer melhores resultados no mercado de trabalho. Mas só se realmente você seguir corretamente as disciplinas da educação clássica e as estudar com paciência. Pois lembre-se; você está estudando para desenvolver o seu espírito, para conseguir entender a realidade em sua volta, e com isso viver bem e tirar bons frutos disso.\n\nSobre como começar a estudar, recomendo, inicialmente, logo de cara, a leitura dos grandes escritores brasileiros. O estudo do latim, e a recitação de poemas e prosas. Mas como ainda estou estudando as disciplinas, como um mero e simples aluno. Recomendo aqui o livro da Irmã Miriam Joseph; As Artes Liberais. O instituto borborema. O instituto Hugo de São Vítor. Só tenho a capacidade de recomendar até o momento os mesmos.\n\nPois, entendendo a ideia da educação clássica, você vai conseguir lidar melhor com o problema que a maioria dos Brasileiros sofre, que é a falta de uma boa educação. Seja se você está no ensino primário ou secundário, e principalmente no ensino superior. Você vai ter inteligência para saber o que deve estudar, e como estudar. Não se preocupe, sempre temos o tempo, se estamos respirando, temos o tempo, e com o tempo é possível mudar tudo, só não as leis de Deus. Chego ao fim.\n\n',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo11
  {
    '8v2vogu0': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'i6mwx6ch': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '8g7n53zs': {
      'pt': 'Música',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd9zolno6': {
      'pt': 'Aqui está uma boa lista de boas músicas.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yx2qyzjb': {
      'pt':
          'Aqui estão uma boa lista de boas músicas, que te ensinaram por apenas as escutar; A valorizar coisas boas, a ter paciência, e sobretudo a desenvolver sua inteligência. Faça o teste e verá o que eu estou dizendo.\n\nLista:\n\n1– 5ª Sinfonia em Dó Menor Op. 67 ou Sinfonia do Destino — Beethoven\n\n2– Infernal Galop, de Orfeu no Submundo — Offenbach\n\n3 – Brindisi, La Traviata — Giuseppe Verdi\n\n4 – O Barbeiro de Sevilha — Gioachino Rossini\n\n5 – Rapsódia Húngara nº 2 — Franz Liszt\n\n6 – Noturno Opus 9 Nº 2 — Chopin\n\n7 – Abertura de William Tell, ou Guilherme Tell — Rossini\n\n8 – Valsa, de A Bela Adormecida — Tchaikovsky\n\n9 – A Entrada dos Gladiadores — Fucik\n\n10 – Dança Macabra — Saint-Säens\n',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo12
  {
    'yz0zu56i': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cngpavst': {
      'pt':
          '11 – Primavera, de As Quatro Estações — Antonio Vivaldi\n\n12 – Jesu Joy of Man’s Desiring, Cantata 147 — Johann Sebastian Bach\n\n13 – Für Elise — Ludwig Van Beethoven\n\n14 – Con Te Partirò — Francesco Sartori e Lucio Quarantotto\n\n15 – O Sole Mio — Eduardo di Capua e Alfredo Mazzuchi\n\n16 – Alla Turca ou Sonata para Piano nº 11 — Wolfgang Amadeus Mozart\n\n17 – Marcha Fúnebre — Frédéric Chopin\n\n18 – Ode à Felicidade — Schiller\n\n19 – Carmina Burana — Carl Orff\n\n20 – Troika — Sergei Prokofiev\n\n21 – Trio para Piano em Lá Menor, Op. 50 — Tchaikovsky\n\n22 – Bolero — Ravel\n\n23 – Tocata e Fuga em D Menor (c. XVIII) — Bach\n\n24 – Trenzinho caipira — Villa-Lobos\n\nEssa lista foi tirada do site do Brasil Paralelo; https://www.brasilparalelo.com.br/artigos/musicas-classicas-mais-famosas\n\nRecomendo que leiam o artigo para descobrir mais músicas clássicas.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo13
  {
    'w94wjryy': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1q18r7p1': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'n3igptjw': {
      'pt': 'Frases',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'knld4w8y': {
      'pt': 'Frases dos sábios.',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vzzdoxff': {
      'pt':
          '“Querem estar sempre satisfeitos e risonhos? É a obediência que nos leva a essa alegria.” \nDom Bosco\n\n“Ser bom não consiste em não cometer falhas, mas na vontade de corrigir-se.” \nDom Bosco\n\n“Não adianta nada ficar lamentando os males, é preciso arregaçar as mangas e dar de tudo para eliminá-los.” \nDom Bosco\n\n“A desobediência é a raiz de todo mal.”\nDom Bosco\n\n“Faça o bem a todos e não faça mal a ninguém.” Dom Bosco\n\n“Perdoe tudo aos outros, mas não faça nada a si mesmo.” \nDom Bosco\n\n“Tenha coragem diante de sua fé e suas convicções. São os maus que devem temer diante dos bons, e não os bons diante dos maus.”\nDom Bosco\n\n“A mais fiel companheira da alma é a esperança.”\nPadre Antônio Vieira\n',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo14
  {
    '5ygspovr': {
      'pt': 'Próxima',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ibzp9ss5': {
      'pt':
          '\n“Instruir é construir.”\nPadre Antônio Vieira\n\n“O País começa, com religião e alta cultura. Foi a religião que criou o Brasil, foi a religião que criou todos os países do mundo.”\nOlavo de Carvalho\n\n“A educação é a grande arte de formar homens.”\nDom Bosco\n\n“Educação é formar honestos cidadãos e bons cristãos.”\nDom Bosco\n\n“A vida é um dom, um dever, um talento a desenvolver, um empenho, uma missão a realizar.” \nDom Bosco\n\n\n“Nossa vida é um presente de Deus e o que fazemos dela é nosso presente a ele.”\nDom Bosco\n\n“Ser bom não consiste em não cometer falhas, mas na vontade de corrigir-se.”\nDom Bosco\n\n“O melhor modo de fazer bem as coisas é fazê-las na presença de Deus.”\nDom Bosco',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Paginaartigo15
  {
    'r9q4io5l': {
      'pt': 'Voltar',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'e659q5aa': {
      'pt':
          '“Não deixem para amanhã o bem que podem fazer hoje: amanhã poderia lhes faltar o tempo.”\nDom Bosco\n\n“Querem estar sempre satisfeitos e risonhos? É a obediência que nos leva a essa alegria.”\nDom Bosco\n\n“Perdoe tudo aos outros, mas não faça nada a si mesmo.”\nDom Bosco\n\n“Faça o bem a todos e não faça mal a ninguém.”\nDom Bosco\n\nFim!',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Miscellaneous
  {
    'hiok7ok8': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ywuym0ht': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'yp7i5mjc': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '47qexfef': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v4s5wfzt': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v83zpgmc': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kwnn38k9': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm73rrfti': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f0as9sek': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9vb2wn2k': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eq00lrmm': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hjchs4r1': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u9p6wpfh': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2e5jfb0u': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y1pxe9ze': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd2yl3fgd': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6jay2tgo': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'i919lkgg': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jh78fp16': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u2lq8p0j': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '775prcfa': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eim5floc': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f492yqc2': {
      'pt': '',
      'af': '',
      'ar': '',
      'de': '',
      'en': '',
      'es': '',
      'fr': '',
      'gl': '',
      'id': '',
      'it': '',
      'kg': '',
      'ko': '',
      'la': '',
      'ro': '',
      'ru': '',
      'uk': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
